let data = [
  {
    id: 1,
    title: "Exploring the Wonders of Machine Learning",
    img: "https://www.simplilearn.com/ice9/free_resources_article_thumb/Deep-Learning-vs-Machine-Learning.jpg",
    body: "In this blog post, we delve into the fascinating world of machine learning, exploring its applications, challenges, and the impact it has on various industries.",
    date: "2023-01-05",
    author: "John Doe",
    content: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer eget justo nec elit ultrices venenatis. Ut vel cursus metus. Nullam vel ex vitae odio convallis tincidunt. Sed nec velit non augue tristique faucibus. Ut ac scelerisque orci. Vestibulum eleifend lacus nec neque imperdiet, ac eleifend turpis blandit. Curabitur vel venenatis sapien. Fusce sodales gravida urna, non euismod ligula ultrices quis. Donec vel nisi purus. Phasellus eu dui dolor. Ut euismod, sem vel hendrerit fermentum, sem libero elementum turpis, nec suscipit elit odio vel justo. Fusce efficitur augue eu quam facilisis, ut vestibulum lacus iaculis. Sed at justo nec ligula varius cursus. Nam sodales elit nec neque bibendum, et mattis nisi aliquam. Proin ut velit a orci ultrices tincidunt. Praesent eget mauris a metus commodo lacinia. Vivamus at ligula sit amet tortor efficitur posuere. Pellentesque vel velit vel nulla iaculis tristique.",
  },
  {
    id: 2,
    title: "The Art of Web Development: A Comprehensive Guide",
    img: "https://cdn5.vectorstock.com/i/1000x1000/06/54/web-development-line-art-banner-site-vector-14840654.jpg",
    body: "Discover the key principles and best practices in web development. From front-end design to back-end technologies, this guide covers it all, making it an essential read for aspiring developers.",
    date: "2023-02-15",
    author: "Jane Smith",
    content: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer eget justo nec elit ultrices venenatis. Ut vel cursus metus. Nullam vel ex vitae odio convallis tincidunt. Sed nec velit non augue tristique faucibus. Ut ac scelerisque orci. Vestibulum eleifend lacus nec neque imperdiet, ac eleifend turpis blandit. Curabitur vel venenatis sapien. Fusce sodales gravida urna, non euismod ligula ultrices quis. Donec vel nisi purus. Phasellus eu dui dolor. Ut euismod, sem vel hendrerit fermentum, sem libero elementum turpis, nec suscipit elit odio vel justo. Fusce efficitur augue eu quam facilisis, ut vestibulum lacus iaculis. Sed at justo nec ligula varius cursus. Nam sodales elit nec neque bibendum, et mattis nisi aliquam. Proin ut velit a orci ultrices tincidunt. Praesent eget mauris a metus commodo lacinia. Vivamus at ligula sit amet tortor efficitur posuere. Pellentesque vel velit vel nulla iaculis tristique.",
  },
  {
    id: 3,
    title: "Unlocking Creativity: A Journey Through Writing",
    img: "https://benjaminmcevoy.com/wp-content/uploads/2016/08/how-to-unlock-creativity-before-writing.jpg",
    body: "Join me on a journey through the creative process of writing. We'll explore techniques, overcome common challenges, and find inspiration to fuel your passion for storytelling.",
    date: "2023-03-20",
    author: "Alex Turner",
    content: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer eget justo nec elit ultrices venenatis. Ut vel cursus metus. Nullam vel ex vitae odio convallis tincidunt. Sed nec velit non augue tristique faucibus. Ut ac scelerisque orci. Vestibulum eleifend lacus nec neque imperdiet, ac eleifend turpis blandit. Curabitur vel venenatis sapien. Fusce sodales gravida urna, non euismod ligula ultrices quis. Donec vel nisi purus. Phasellus eu dui dolor. Ut euismod, sem vel hendrerit fermentum, sem libero elementum turpis, nec suscipit elit odio vel justo. Fusce efficitur augue eu quam facilisis, ut vestibulum lacus iaculis. Sed at justo nec ligula varius cursus. Nam sodales elit nec neque bibendum, et mattis nisi aliquam. Proin ut velit a orci ultrices tincidunt. Praesent eget mauris a metus commodo lacinia. Vivamus at ligula sit amet tortor efficitur posuere. Pellentesque vel velit vel nulla iaculis tristique.",
  },
  {
    id: 4,
    title: "The Future of Space Exploration: Beyond Our Imagination",
    img: "https://miro.medium.com/v2/resize:fit:1400/1*mbFv_ei9Nii7vrMjRZuHJg.jpeg",
    body: "As we push the boundaries of space exploration, this blog post examines the latest advancements, upcoming missions, and the potential for humanity to reach new frontiers.",
    date: "2023-04-10",
    author: "Emily Chang",
    content: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer eget justo nec elit ultrices venenatis. Ut vel cursus metus. Nullam vel ex vitae odio convallis tincidunt. Sed nec velit non augue tristique faucibus. Ut ac scelerisque orci. Vestibulum eleifend lacus nec neque imperdiet, ac eleifend turpis blandit. Curabitur vel venenatis sapien. Fusce sodales gravida urna, non euismod ligula ultrices quis. Donec vel nisi purus. Phasellus eu dui dolor. Ut euismod, sem vel hendrerit fermentum, sem libero elementum turpis, nec suscipit elit odio vel justo. Fusce efficitur augue eu quam facilisis, ut vestibulum lacus iaculis. Sed at justo nec ligula varius cursus. Nam sodales elit nec neque bibendum, et mattis nisi aliquam. Proin ut velit a orci ultrices tincidunt. Praesent eget mauris a metus commodo lacinia. Vivamus at ligula sit amet tortor efficitur posuere. Pellentesque vel velit vel nulla iaculis tristique.",
  },
  {
    id: 5,
    title: "Healthy Living: Mind, Body, and Soul",
    img: "https://d2y24eux71xwor.cloudfront.net/Images/Production/Content/Series/786009-en.jpg",
    body: "Explore the pillars of a healthy lifestyle, including physical fitness, mental well-being, and spiritual nourishment. Learn practical tips for incorporating wellness into your daily routine.",
    date: "2023-05-02",
    author: "David Johnson",
    content: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer eget justo nec elit ultrices venenatis. Ut vel cursus metus. Nullam vel ex vitae odio convallis tincidunt. Sed nec velit non augue tristique faucibus. Ut ac scelerisque orci. Vestibulum eleifend lacus nec neque imperdiet, ac eleifend turpis blandit. Curabitur vel venenatis sapien. Fusce sodales gravida urna, non euismod ligula ultrices quis. Donec vel nisi purus. Phasellus eu dui dolor. Ut euismod, sem vel hendrerit fermentum, sem libero elementum turpis, nec suscipit elit odio vel justo. Fusce efficitur augue eu quam facilisis, ut vestibulum lacus iaculis. Sed at justo nec ligula varius cursus. Nam sodales elit nec neque bibendum, et mattis nisi aliquam. Proin ut velit a orci ultrices tincidunt. Praesent eget mauris a metus commodo lacinia. Vivamus at ligula sit amet tortor efficitur posuere. Pellentesque vel velit vel nulla iaculis tristique.",
  },
  {
    id: 6,
    title: "Navigating the Digital Landscape: A Guide for Entrepreneurs",
    img: "https://media.licdn.com/dms/image/D4D12AQHqEumXetYkgQ/article-cover_image-shrink_600_2000/0/1692443065091?e=2147483647&v=beta&t=elMJTOhf86jlbI0C9b5SuH537GeSVbzVsC4nc3OiMLo",
    body: "For aspiring entrepreneurs, this guide offers insights into the digital landscape. From building an online presence to leveraging social media, discover the strategies for success.",
    date: "2023-06-18",
    author: "Sarah Patel",
    content: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer eget justo nec elit ultrices venenatis. Ut vel cursus metus. Nullam vel ex vitae odio convallis tincidunt. Sed nec velit non augue tristique faucibus. Ut ac scelerisque orci. Vestibulum eleifend lacus nec neque imperdiet, ac eleifend turpis blandit. Curabitur vel venenatis sapien. Fusce sodales gravida urna, non euismod ligula ultrices quis. Donec vel nisi purus. Phasellus eu dui dolor. Ut euismod, sem vel hendrerit fermentum, sem libero elementum turpis, nec suscipit elit odio vel justo. Fusce efficitur augue eu quam facilisis, ut vestibulum lacus iaculis. Sed at justo nec ligula varius cursus. Nam sodales elit nec neque bibendum, et mattis nisi aliquam. Proin ut velit a orci ultrices tincidunt. Praesent eget mauris a metus commodo lacinia. Vivamus at ligula sit amet tortor efficitur posuere. Pellentesque vel velit vel nulla iaculis tristique.",
  },
  {
    id: 7,
    title: "The Impact of Renewable Energy on Climate Change",
    img: "https://ars.els-cdn.com/content/image/1-s2.0-S1364032119306239-gr1.jpg",
    body: "Delve into the role of renewable energy in combating climate change. This blog post explores the environmental benefits, challenges, and the global effort to transition to sustainable energy sources.",
    date: "2023-07-07",
    author: "Michael Rodriguez",
    content: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer eget justo nec elit ultrices venenatis. Ut vel cursus metus. Nullam vel ex vitae odio convallis tincidunt. Sed nec velit non augue tristique faucibus. Ut ac scelerisque orci. Vestibulum eleifend lacus nec neque imperdiet, ac eleifend turpis blandit. Curabitur vel venenatis sapien. Fusce sodales gravida urna, non euismod ligula ultrices quis. Donec vel nisi purus. Phasellus eu dui dolor. Ut euismod, sem vel hendrerit fermentum, sem libero elementum turpis, nec suscipit elit odio vel justo. Fusce efficitur augue eu quam facilisis, ut vestibulum lacus iaculis. Sed at justo nec ligula varius cursus. Nam sodales elit nec neque bibendum, et mattis nisi aliquam. Proin ut velit a orci ultrices tincidunt. Praesent eget mauris a metus commodo lacinia. Vivamus at ligula sit amet tortor efficitur posuere. Pellentesque vel velit vel nulla iaculis tristique.",
  },
  {
    id: 8,
    title: "Artificial Intelligence: Shaping the Future of Healthcare",
    img: "https://www.mouser.in/blog/Portals/11/Vaitheeswaran_AI%20Shaping%20Healthcare_Theme%20Image-min.jpg",
    body: "Learn how AI is revolutionizing the healthcare industry, from diagnostics to personalized treatment plans. Explore the potential benefits and ethical considerations of AI in medicine.",
    date: "2023-08-23",
    author: "Olivia Lee",
    content: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer eget justo nec elit ultrices venenatis. Ut vel cursus metus. Nullam vel ex vitae odio convallis tincidunt. Sed nec velit non augue tristique faucibus. Ut ac scelerisque orci. Vestibulum eleifend lacus nec neque imperdiet, ac eleifend turpis blandit. Curabitur vel venenatis sapien. Fusce sodales gravida urna, non euismod ligula ultrices quis. Donec vel nisi purus. Phasellus eu dui dolor. Ut euismod, sem vel hendrerit fermentum, sem libero elementum turpis, nec suscipit elit odio vel justo. Fusce efficitur augue eu quam facilisis, ut vestibulum lacus iaculis. Sed at justo nec ligula varius cursus. Nam sodales elit nec neque bibendum, et mattis nisi aliquam. Proin ut velit a orci ultrices tincidunt. Praesent eget mauris a metus commodo lacinia. Vivamus at ligula sit amet tortor efficitur posuere. Pellentesque vel velit vel nulla iaculis tristique.",
  },
  {
    id: 9,
    title: "Culinary Adventures: A Tour of Global Flavors",
    img: "https://m.media-amazon.com/images/W/MEDIAX_792452-T2/images/I/51McbTCjNdL._SR600%2C315_PIWhiteStrip%2CBottomLeft%2C0%2C35_SCLZZZZZZZ_FMpng_BG255%2C255%2C255.jpg",
    body: "Embark on a culinary journey around the world as we explore diverse cuisines, traditional recipes, and the stories behind each dish. Get ready for a mouth-watering adventure!",
    date: "2023-09-14",
    author: "Carlos Sanchez",
    content: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer eget justo nec elit ultrices venenatis. Ut vel cursus metus. Nullam vel ex vitae odio convallis tincidunt. Sed nec velit non augue tristique faucibus. Ut ac scelerisque orci. Vestibulum eleifend lacus nec neque imperdiet, ac eleifend turpis blandit. Curabitur vel venenatis sapien. Fusce sodales gravida urna, non euismod ligula ultrices quis. Donec vel nisi purus. Phasellus eu dui dolor. Ut euismod, sem vel hendrerit fermentum, sem libero elementum turpis, nec suscipit elit odio vel justo. Fusce efficitur augue eu quam facilisis, ut vestibulum lacus iaculis. Sed at justo nec ligula varius cursus. Nam sodales elit nec neque bibendum, et mattis nisi aliquam. Proin ut velit a orci ultrices tincidunt. Praesent eget mauris a metus commodo lacinia. Vivamus at ligula sit amet tortor efficitur posuere. Pellentesque vel velit vel nulla iaculis tristique.",
  },
  {
    id: 10,
    title: "Navigating the Remote Work Landscape",
    img: "https://media.licdn.com/dms/image/D5612AQHT9hZgmD9hCw/article-cover_image-shrink_600_2000/0/1700108924216?e=2147483647&v=beta&t=G97bnlSWvTbuiKuQuD69v08J3E7VJz5TXkBpS3qpJTg",
    body: "With the rise of remote work, this blog post provides insights into effective strategies for working from home. From setting up a productive workspace to maintaining work-life balance, discover the keys to remote success.",
    date: "2023-10-30",
    author: "Lauren Miller",
    content: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer eget justo nec elit ultrices venenatis. Ut vel cursus metus. Nullam vel ex vitae odio convallis tincidunt. Sed nec velit non augue tristique faucibus. Ut ac scelerisque orci. Vestibulum eleifend lacus nec neque imperdiet, ac eleifend turpis blandit. Curabitur vel venenatis sapien. Fusce sodales gravida urna, non euismod ligula ultrices quis. Donec vel nisi purus. Phasellus eu dui dolor. Ut euismod, sem vel hendrerit fermentum, sem libero elementum turpis, nec suscipit elit odio vel justo. Fusce efficitur augue eu quam facilisis, ut vestibulum lacus iaculis. Sed at justo nec ligula varius cursus. Nam sodales elit nec neque bibendum, et mattis nisi aliquam. Proin ut velit a orci ultrices tincidunt. Praesent eget mauris a metus commodo lacinia. Vivamus at ligula sit amet tortor efficitur posuere. Pellentesque vel velit vel nulla iaculis tristique.",
  },
  {
    id: 11,
    title: "Innovations in Robotics: A Glimpse into the Future",
    img: "https://imageio.forbes.com/specials-images/imageserve/628b8de7a18d8436b8782e88/0x0.jpg?format=jpg&height=600&width=1200&fit=bounds",
    body: "Explore the latest advancements in robotics and the transformative impact they are having on industries such as manufacturing, healthcare, and beyond.",
    date: "2023-11-15",
    author: "Christopher Anderson",
    content: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer eget justo nec elit ultrices venenatis. Ut vel cursus metus. Nullam vel ex vitae odio convallis tincidunt. Sed nec velit non augue tristique faucibus. Ut ac scelerisque orci. Vestibulum eleifend lacus nec neque imperdiet, ac eleifend turpis blandit. Curabitur vel venenatis sapien. Fusce sodales gravida urna, non euismod ligula ultrices quis. Donec vel nisi purus. Phasellus eu dui dolor. Ut euismod, sem vel hendrerit fermentum, sem libero elementum turpis, nec suscipit elit odio vel justo. Fusce efficitur augue eu quam facilisis, ut vestibulum lacus iaculis. Sed at justo nec ligula varius cursus. Nam sodales elit nec neque bibendum, et mattis nisi aliquam. Proin ut velit a orci ultrices tincidunt. Praesent eget mauris a metus commodo lacinia. Vivamus at ligula sit amet tortor efficitur posuere. Pellentesque vel velit vel nulla iaculis tristique.",
  },
  {
    id: 12,
    title:
      "The World of Cryptocurrency: Decoding the Digital Currency Revolution",
    img: "https://miro.medium.com/v2/resize:fit:1140/1*VUod-acM_42M1pGtplXyZQ.jpeg",
    body: "Dive into the world of cryptocurrency and blockchain technology. Understand the concepts, potential applications, and the evolving landscape of digital currencies.",
    date: "2023-12-02",
    author: "Sophia Thompson",
    content: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer eget justo nec elit ultrices venenatis. Ut vel cursus metus. Nullam vel ex vitae odio convallis tincidunt. Sed nec velit non augue tristique faucibus. Ut ac scelerisque orci. Vestibulum eleifend lacus nec neque imperdiet, ac eleifend turpis blandit. Curabitur vel venenatis sapien. Fusce sodales gravida urna, non euismod ligula ultrices quis. Donec vel nisi purus. Phasellus eu dui dolor. Ut euismod, sem vel hendrerit fermentum, sem libero elementum turpis, nec suscipit elit odio vel justo. Fusce efficitur augue eu quam facilisis, ut vestibulum lacus iaculis. Sed at justo nec ligula varius cursus. Nam sodales elit nec neque bibendum, et mattis nisi aliquam. Proin ut velit a orci ultrices tincidunt. Praesent eget mauris a metus commodo lacinia. Vivamus at ligula sit amet tortor efficitur posuere. Pellentesque vel velit vel nulla iaculis tristique.",
  },
  {
    id: 13,
    title: "Mindfulness Meditation: Cultivating Peace in a Busy World",
    img: "https://m.media-amazon.com/images/I/61LSSUIz6eL._AC_UF894,1000_QL80_.jpg",
    body: "Learn about the practice of mindfulness meditation and its profound impact on mental well-being. Discover techniques to bring mindfulness into your daily life.",
    date: "2024-01-10",
    author: "Elena Rodriguez",
    content: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer eget justo nec elit ultrices venenatis. Ut vel cursus metus. Nullam vel ex vitae odio convallis tincidunt. Sed nec velit non augue tristique faucibus. Ut ac scelerisque orci. Vestibulum eleifend lacus nec neque imperdiet, ac eleifend turpis blandit. Curabitur vel venenatis sapien. Fusce sodales gravida urna, non euismod ligula ultrices quis. Donec vel nisi purus. Phasellus eu dui dolor. Ut euismod, sem vel hendrerit fermentum, sem libero elementum turpis, nec suscipit elit odio vel justo. Fusce efficitur augue eu quam facilisis, ut vestibulum lacus iaculis. Sed at justo nec ligula varius cursus. Nam sodales elit nec neque bibendum, et mattis nisi aliquam. Proin ut velit a orci ultrices tincidunt. Praesent eget mauris a metus commodo lacinia. Vivamus at ligula sit amet tortor efficitur posuere. Pellentesque vel velit vel nulla iaculis tristique.",
  },
  {
    id: 14,
    title: "Exploring Ancient Civilizations: Unraveling Mysteries of the Past",
    img: "https://media.newstrack.in/amp/uploads/other-news/trending-news/Jul/07/big_thumb/ac_64a7a04a05949.JPG",
    body: "Embark on a historical journey to explore the wonders of ancient civilizations. Uncover archaeological finds, decipher ancient texts, and unravel the mysteries of our ancestors.",
    date: "2024-02-18",
    author: "Daniel Carter",
    content: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer eget justo nec elit ultrices venenatis. Ut vel cursus metus. Nullam vel ex vitae odio convallis tincidunt. Sed nec velit non augue tristique faucibus. Ut ac scelerisque orci. Vestibulum eleifend lacus nec neque imperdiet, ac eleifend turpis blandit. Curabitur vel venenatis sapien. Fusce sodales gravida urna, non euismod ligula ultrices quis. Donec vel nisi purus. Phasellus eu dui dolor. Ut euismod, sem vel hendrerit fermentum, sem libero elementum turpis, nec suscipit elit odio vel justo. Fusce efficitur augue eu quam facilisis, ut vestibulum lacus iaculis. Sed at justo nec ligula varius cursus. Nam sodales elit nec neque bibendum, et mattis nisi aliquam. Proin ut velit a orci ultrices tincidunt. Praesent eget mauris a metus commodo lacinia. Vivamus at ligula sit amet tortor efficitur posuere. Pellentesque vel velit vel nulla iaculis tristique.",
  },
  {
    id: 15,
    title: "The Future of Augmented Reality: Transforming How We See the World",
    img: "https://www.technology-innovators.com/wp-content/uploads/2023/05/The-Future-of-ARVR-Transforming-the-Way-We-See-and-Interact-with-the-World-min.jpg",
    body: "Delve into the evolving landscape of augmented reality (AR) technology. Discover its current applications, potential future developments, and the impact on various industries.",
    date: "2024-03-05",
    author: "Isabella Martin",
    content: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer eget justo nec elit ultrices venenatis. Ut vel cursus metus. Nullam vel ex vitae odio convallis tincidunt. Sed nec velit non augue tristique faucibus. Ut ac scelerisque orci. Vestibulum eleifend lacus nec neque imperdiet, ac eleifend turpis blandit. Curabitur vel venenatis sapien. Fusce sodales gravida urna, non euismod ligula ultrices quis. Donec vel nisi purus. Phasellus eu dui dolor. Ut euismod, sem vel hendrerit fermentum, sem libero elementum turpis, nec suscipit elit odio vel justo. Fusce efficitur augue eu quam facilisis, ut vestibulum lacus iaculis. Sed at justo nec ligula varius cursus. Nam sodales elit nec neque bibendum, et mattis nisi aliquam. Proin ut velit a orci ultrices tincidunt. Praesent eget mauris a metus commodo lacinia. Vivamus at ligula sit amet tortor efficitur posuere. Pellentesque vel velit vel nulla iaculis tristique.",
  },
  {
    id: 16,
    title:
      "Sustainable Fashion: Redefining Style with Environmental Consciousness",
    img: "https://miro.medium.com/v2/resize:fit:1000/0*yzd7pb70h5Y71BcM.jpeg",
    body: "Explore the world of sustainable fashion and its growing influence on the fashion industry. Learn about eco-friendly materials, ethical practices, and the push for a more sustainable wardrobe.",
    date: "2024-04-22",
    author: "Lucas Garcia",
    content: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer eget justo nec elit ultrices venenatis. Ut vel cursus metus. Nullam vel ex vitae odio convallis tincidunt. Sed nec velit non augue tristique faucibus. Ut ac scelerisque orci. Vestibulum eleifend lacus nec neque imperdiet, ac eleifend turpis blandit. Curabitur vel venenatis sapien. Fusce sodales gravida urna, non euismod ligula ultrices quis. Donec vel nisi purus. Phasellus eu dui dolor. Ut euismod, sem vel hendrerit fermentum, sem libero elementum turpis, nec suscipit elit odio vel justo. Fusce efficitur augue eu quam facilisis, ut vestibulum lacus iaculis. Sed at justo nec ligula varius cursus. Nam sodales elit nec neque bibendum, et mattis nisi aliquam. Proin ut velit a orci ultrices tincidunt. Praesent eget mauris a metus commodo lacinia. Vivamus at ligula sit amet tortor efficitur posuere. Pellentesque vel velit vel nulla iaculis tristique.",
  },
  {
    id: 17,
    title: "The Renaissance of Traditional Crafts: Artisanal Revival",
    img: "https://miro.medium.com/v2/resize:fit:1400/1*pfpaBWEW0flT99OuwrUssw.png",
    body: "Witness the resurgence of traditional crafts in the modern era. Discover artisans preserving ancient techniques, creating unique handcrafted products, and contributing to a cultural renaissance.",
    date: "2024-05-15",
    author: "Sophie Williams",
    content: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer eget justo nec elit ultrices venenatis. Ut vel cursus metus. Nullam vel ex vitae odio convallis tincidunt. Sed nec velit non augue tristique faucibus. Ut ac scelerisque orci. Vestibulum eleifend lacus nec neque imperdiet, ac eleifend turpis blandit. Curabitur vel venenatis sapien. Fusce sodales gravida urna, non euismod ligula ultrices quis. Donec vel nisi purus. Phasellus eu dui dolor. Ut euismod, sem vel hendrerit fermentum, sem libero elementum turpis, nec suscipit elit odio vel justo. Fusce efficitur augue eu quam facilisis, ut vestibulum lacus iaculis. Sed at justo nec ligula varius cursus. Nam sodales elit nec neque bibendum, et mattis nisi aliquam. Proin ut velit a orci ultrices tincidunt. Praesent eget mauris a metus commodo lacinia. Vivamus at ligula sit amet tortor efficitur posuere. Pellentesque vel velit vel nulla iaculis tristique.",
  },
  {
    id: 18,
    title:
      "The Psychology of Happiness: Unlocking the Secrets to a Fulfilling Life",
    img: "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1682309924i/139403369.jpg",
    body: "Delve into the science of happiness and well-being. Explore psychological principles, positive habits, and the pursuit of a fulfilling life.",
    date: "2024-06-08",
    author: "Matthew Turner",
    content: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer eget justo nec elit ultrices venenatis. Ut vel cursus metus. Nullam vel ex vitae odio convallis tincidunt. Sed nec velit non augue tristique faucibus. Ut ac scelerisque orci. Vestibulum eleifend lacus nec neque imperdiet, ac eleifend turpis blandit. Curabitur vel venenatis sapien. Fusce sodales gravida urna, non euismod ligula ultrices quis. Donec vel nisi purus. Phasellus eu dui dolor. Ut euismod, sem vel hendrerit fermentum, sem libero elementum turpis, nec suscipit elit odio vel justo. Fusce efficitur augue eu quam facilisis, ut vestibulum lacus iaculis. Sed at justo nec ligula varius cursus. Nam sodales elit nec neque bibendum, et mattis nisi aliquam. Proin ut velit a orci ultrices tincidunt. Praesent eget mauris a metus commodo lacinia. Vivamus at ligula sit amet tortor efficitur posuere. Pellentesque vel velit vel nulla iaculis tristique.",
  },
  {
    id: 19,
    title: "Journey Through Classical Music: Exploring Timeless Masterpieces",
    img: "https://i.ytimg.com/vi/Pc5CDnfLr-M/maxresdefault.jpg",
    body: "Embark on a musical journey through the world of classical music. Discover timeless masterpieces, influential composers, and the enduring beauty of orchestral compositions.",
    date: "2024-07-20",
    author: "Lily Johnson",
    content: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer eget justo nec elit ultrices venenatis. Ut vel cursus metus. Nullam vel ex vitae odio convallis tincidunt. Sed nec velit non augue tristique faucibus. Ut ac scelerisque orci. Vestibulum eleifend lacus nec neque imperdiet, ac eleifend turpis blandit. Curabitur vel venenatis sapien. Fusce sodales gravida urna, non euismod ligula ultrices quis. Donec vel nisi purus. Phasellus eu dui dolor. Ut euismod, sem vel hendrerit fermentum, sem libero elementum turpis, nec suscipit elit odio vel justo. Fusce efficitur augue eu quam facilisis, ut vestibulum lacus iaculis. Sed at justo nec ligula varius cursus. Nam sodales elit nec neque bibendum, et mattis nisi aliquam. Proin ut velit a orci ultrices tincidunt. Praesent eget mauris a metus commodo lacinia. Vivamus at ligula sit amet tortor efficitur posuere. Pellentesque vel velit vel nulla iaculis tristique.",
  },
  {
    id: 20,
    title:
      "Mind-Blowing Architectural Wonders: Icons of Design and Engineering",
    img: "https://media.gq.com/photos/5b6b20e3a3a1320b7280f029/master/pass/The-Brutal-Wonders-Of-The-Architecture-World-GQ-Style-Fall-2018_07.jpg",
    body: "Explore architectural marvels from around the globe. From ancient structures to modern skyscrapers, delve into the awe-inspiring world of design and engineering.",
    date: "2024-08-12",
    author: "Andrew Miller",
    content: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer eget justo nec elit ultrices venenatis. Ut vel cursus metus. Nullam vel ex vitae odio convallis tincidunt. Sed nec velit non augue tristique faucibus. Ut ac scelerisque orci. Vestibulum eleifend lacus nec neque imperdiet, ac eleifend turpis blandit. Curabitur vel venenatis sapien. Fusce sodales gravida urna, non euismod ligula ultrices quis. Donec vel nisi purus. Phasellus eu dui dolor. Ut euismod, sem vel hendrerit fermentum, sem libero elementum turpis, nec suscipit elit odio vel justo. Fusce efficitur augue eu quam facilisis, ut vestibulum lacus iaculis. Sed at justo nec ligula varius cursus. Nam sodales elit nec neque bibendum, et mattis nisi aliquam. Proin ut velit a orci ultrices tincidunt. Praesent eget mauris a metus commodo lacinia. Vivamus at ligula sit amet tortor efficitur posuere. Pellentesque vel velit vel nulla iaculis tristique.",
  },
  {
    id: 21,
    title: "The Power of Storytelling: Crafting Compelling Narratives",
    img: "https://media.licdn.com/dms/image/D4D12AQGGaOsbjPzmTg/article-cover_image-shrink_720_1280/0/1701856743237?e=2147483647&v=beta&t=bsS6Fi5vGRUc1sScK3LupIY0NAIdJaOIp-UFT1raTAQ",
    body: "Unlock the secrets of powerful storytelling. Learn the art of crafting compelling narratives that captivate audiences and leave a lasting impact.",
    date: "2024-09-25",
    author: "Emma Turner",
    content: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer eget justo nec elit ultrices venenatis. Ut vel cursus metus. Nullam vel ex vitae odio convallis tincidunt. Sed nec velit non augue tristique faucibus. Ut ac scelerisque orci. Vestibulum eleifend lacus nec neque imperdiet, ac eleifend turpis blandit. Curabitur vel venenatis sapien. Fusce sodales gravida urna, non euismod ligula ultrices quis. Donec vel nisi purus. Phasellus eu dui dolor. Ut euismod, sem vel hendrerit fermentum, sem libero elementum turpis, nec suscipit elit odio vel justo. Fusce efficitur augue eu quam facilisis, ut vestibulum lacus iaculis. Sed at justo nec ligula varius cursus. Nam sodales elit nec neque bibendum, et mattis nisi aliquam. Proin ut velit a orci ultrices tincidunt. Praesent eget mauris a metus commodo lacinia. Vivamus at ligula sit amet tortor efficitur posuere. Pellentesque vel velit vel nulla iaculis tristique.",
  },
  {
    id: 22,
    title: "Mysteries of the Deep: Exploring the Enigmatic World of the Ocean",
    img: "https://miro.medium.com/v2/resize:fit:912/1*WsCxgKgUFlvn34ukftP5oA.jpeg",
    body: "Dive into the mysteries of the ocean depths. Explore underwater wonders, marine life, and the ongoing exploration of Earth's largest and least-explored frontier.",
    date: "2024-10-10",
    author: "Aiden Davis",
    content: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer eget justo nec elit ultrices venenatis. Ut vel cursus metus. Nullam vel ex vitae odio convallis tincidunt. Sed nec velit non augue tristique faucibus. Ut ac scelerisque orci. Vestibulum eleifend lacus nec neque imperdiet, ac eleifend turpis blandit. Curabitur vel venenatis sapien. Fusce sodales gravida urna, non euismod ligula ultrices quis. Donec vel nisi purus. Phasellus eu dui dolor. Ut euismod, sem vel hendrerit fermentum, sem libero elementum turpis, nec suscipit elit odio vel justo. Fusce efficitur augue eu quam facilisis, ut vestibulum lacus iaculis. Sed at justo nec ligula varius cursus. Nam sodales elit nec neque bibendum, et mattis nisi aliquam. Proin ut velit a orci ultrices tincidunt. Praesent eget mauris a metus commodo lacinia. Vivamus at ligula sit amet tortor efficitur posuere. Pellentesque vel velit vel nulla iaculis tristique.",
  },
  {
    id: 23,
    title:
      "The Art of Mindful Parenting: Nurturing the Parent-Child Connection",
    img: "https://m.media-amazon.com/images/I/51YTHfIKaQL.jpg",
    body: "Discover the principles of mindful parenting. Learn techniques to foster a strong parent-child connection, promote emotional well-being, and navigate the challenges of parenthood.",
    date: "2024-11-08",
    author: "Sophia Clark",
    content: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer eget justo nec elit ultrices venenatis. Ut vel cursus metus. Nullam vel ex vitae odio convallis tincidunt. Sed nec velit non augue tristique faucibus. Ut ac scelerisque orci. Vestibulum eleifend lacus nec neque imperdiet, ac eleifend turpis blandit. Curabitur vel venenatis sapien. Fusce sodales gravida urna, non euismod ligula ultrices quis. Donec vel nisi purus. Phasellus eu dui dolor. Ut euismod, sem vel hendrerit fermentum, sem libero elementum turpis, nec suscipit elit odio vel justo. Fusce efficitur augue eu quam facilisis, ut vestibulum lacus iaculis. Sed at justo nec ligula varius cursus. Nam sodales elit nec neque bibendum, et mattis nisi aliquam. Proin ut velit a orci ultrices tincidunt. Praesent eget mauris a metus commodo lacinia. Vivamus at ligula sit amet tortor efficitur posuere. Pellentesque vel velit vel nulla iaculis tristique.",
  },
  {
    id: 24,
    title: "Revolutionizing Education: Innovations in Learning and Teaching",
    img: "https://dwpsgrnoida.com/wp-content/uploads/2023/10/teaching-method.jpeg",
    body: "Explore the innovations shaping the future of education. From personalized learning to cutting-edge technologies, discover the evolving landscape of teaching and learning.",
    date: "2024-12-01",
    author: "Ethan Adams",
    content: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer eget justo nec elit ultrices venenatis. Ut vel cursus metus. Nullam vel ex vitae odio convallis tincidunt. Sed nec velit non augue tristique faucibus. Ut ac scelerisque orci. Vestibulum eleifend lacus nec neque imperdiet, ac eleifend turpis blandit. Curabitur vel venenatis sapien. Fusce sodales gravida urna, non euismod ligula ultrices quis. Donec vel nisi purus. Phasellus eu dui dolor. Ut euismod, sem vel hendrerit fermentum, sem libero elementum turpis, nec suscipit elit odio vel justo. Fusce efficitur augue eu quam facilisis, ut vestibulum lacus iaculis. Sed at justo nec ligula varius cursus. Nam sodales elit nec neque bibendum, et mattis nisi aliquam. Proin ut velit a orci ultrices tincidunt. Praesent eget mauris a metus commodo lacinia. Vivamus at ligula sit amet tortor efficitur posuere. Pellentesque vel velit vel nulla iaculis tristique.",
  },
  {
    id: 25,
    title: "The Science of Sleep: Understanding the Importance of Rest",
    img: "https://www.sleepfoundation.org/wp-content/uploads/2021/12/SF-23-022_SleepCycle_Pie_Desktop-1024x717.png",
    body: "Delve into the science of sleep and its crucial role in overall health. Explore sleep patterns, the impact of sleep on mental well-being, and tips for improving sleep quality.",
    date: "2025-01-15",
    author: "Mia Turner",
    content: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer eget justo nec elit ultrices venenatis. Ut vel cursus metus. Nullam vel ex vitae odio convallis tincidunt. Sed nec velit non augue tristique faucibus. Ut ac scelerisque orci. Vestibulum eleifend lacus nec neque imperdiet, ac eleifend turpis blandit. Curabitur vel venenatis sapien. Fusce sodales gravida urna, non euismod ligula ultrices quis. Donec vel nisi purus. Phasellus eu dui dolor. Ut euismod, sem vel hendrerit fermentum, sem libero elementum turpis, nec suscipit elit odio vel justo. Fusce efficitur augue eu quam facilisis, ut vestibulum lacus iaculis. Sed at justo nec ligula varius cursus. Nam sodales elit nec neque bibendum, et mattis nisi aliquam. Proin ut velit a orci ultrices tincidunt. Praesent eget mauris a metus commodo lacinia. Vivamus at ligula sit amet tortor efficitur posuere. Pellentesque vel velit vel nulla iaculis tristique.",
  },
];

export default data;
